name = "Create With"
author = "hothod2nd"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a92f193b6579ea7e88d2fc638f7b699d05f59d87c9edac6d8f76b2015900155a"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
