name = "Create With"
author = "hothod2nd"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37f861ac27f58e34d57464b651372db75e1e95f3e57559e5890683193acebd15"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
